Fix set_trace(paused=False)
Previously this gave an exception like

>>> pudb._get_debugger().set_trace(paused=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/miniconda3/lib/python3.11/site-packages/pudb/debugger.py", line 291, in set_trace
    self.set_continue()
  File "/Users/aaronmeurer/miniconda3/lib/python3.11/bdb.py", line 344, in set_continue
    self._set_stopinfo(self.botframe, None, -1)
                       ^^^^^^^^^^^^^
AttributeError: 'Debugger' object has no attribute 'botframe'

The fix is to always set the botframe variable, even when paused=False,
because after commit 2b08f08910da00e58df736c719f11ae75bd5333c, the bdb
set_continue method is used, which requires botframe to be set.